dist: xenial
language: python
cache: pip

git:
  depth: 5
  quiet: true

python:
  - "3.6"

install:
  - pip install flake8

script: true
#  - find . -name \*.py -print0 | sort -z | xargs -r0 flake8

