FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

#installing flatpack packaging utilities

RUN apt-get update && apt-get install -y \ 
    build-essential \
    make \
    ccache \
    python3 \
    python3-pip \
    git \
    autoconf \
    sudo \
    flatpak \
    flatpak-builder \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
CMD ["/bin/bash"]
