#!/bin/sh

echo "This is a test script"
echo "========================================"
git --version
echo "========================================"
make --version
echo "========================================"
autoconf --verison
echo "========================================"
