# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(843, 396)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(30, 30, 781, 31))
        self.progressBar.setStyleSheet("QProgressBar::chunk {\n"
"    background-color: rgb(38, 162, 105);\n"
"}")
        self.progressBar.setMaximum(0)
        #self.progressBar.setProperty("value", 100)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.ngspiceConsole = QtWidgets.QPlainTextEdit(Dialog)
        self.ngspiceConsole.setGeometry(QtCore.QRect(30, 80, 781, 281))
        self.ngspiceConsole.setAutoFillBackground(False)
        self.ngspiceConsole.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse)
        self.ngspiceConsole.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgb(36, 31, 49);\n"
"    color: white;\n"
"}")
        self.ngspiceConsole.setObjectName("ngspiceConsole")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        #self.ngspiceConsole.setPlainText(_translate("Dialog", "The Ngspice simulation log will appear here."))

    def writeIntoConsole(self, text):
        self.ngspiceConsole.insertPlainText(text)

    def showProgressCompleted(self):
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 100)
